### PR TITLE
Update values.yaml to include emrcontainers

### PR DESCRIPTION
**Pull request by mikestef9**
Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by RedbackThomson — APPROVED** [review]
Thanks. Must have missed this in my initial commits

/lgtm

**Review by a-hilaly — APPROVED** [review]
👍

**Comment by a-hilaly** [comment]
@mikestef9 looks your branch needs a rebase

**Pull request closed without merging**
